FROM node AS builder

COPY . /opt/frontend

ARG VITE_API_SERVER
ARG VITE_IDP_SERVER
ARG VITE_IDP_CLIENT_ID
ENV VITE_API_SERVER=${VITE_API_SERVER:-https://api.picz.oglimmer.de}
ENV VITE_IDP_SERVER=${VITE_IDP_SERVER:-https://id.oglimmer.de/realms/oglimmer}
ENV VITE_IDP_CLIENT_ID=${VITE_IDP_CLIENT_ID:-picz-client}

RUN cd /opt/frontend && npm i && npm run build

FROM nginx:latest

COPY --from=builder /opt/frontend/dist/index.html /usr/share/nginx/html
COPY --from=builder /opt/frontend/dist/favicon.ico /usr/share/nginx/html
COPY --from=builder /opt/frontend/dist/hash.png /usr/share/nginx/html
COPY --from=builder /opt/frontend/dist/assets /usr/share/nginx/html/assets
COPY --from=builder /opt/frontend/dist/fonts /usr/share/nginx/html/fonts

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
