plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '8.1.0'
}

group = 'de.oglimmer'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = '21'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-mysql'
	implementation 'com.drewnoakes:metadata-extractor:2.19.0'
	implementation 'org.modelmapper:modelmapper:3.2.6'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
//	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation 'com.google.guava:guava:33.5.0-jre'
	implementation 'org.bouncycastle:bcprov-jdk18on:1.83'

	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	implementation platform('software.amazon.awssdk:bom:2.41.3')
	implementation 'software.amazon.awssdk:s3'
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	java {
		googleJavaFormat()
		removeUnusedImports()
		trimTrailingWhitespace()
		endWithNewline()
		licenseHeader '/* Copyright (c) 2025 by oglimmer.com / Oliver Zimpasser. All rights reserved. */'
	}

	format 'markdown', {
		target '**/*.md'
		prettier()
		trimTrailingWhitespace()
		endWithNewline()
	}

	format 'yaml', {
		target '**/*.yml', '**/*.yaml'
		prettier().config(['parser': 'yaml'])
		trimTrailingWhitespace()
		endWithNewline()
	}

	format 'json', {
		target 'src/**/*.json', '**/*.json'
		prettier()
		trimTrailingWhitespace()
		endWithNewline()
	}
}
